FROM node:18

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install

COPY . .

ARG APP_KEYS
ARG API_TOKEN_SALT
ARG ADMIN_JWT_SECRET
ARG JWT_SECRET
ARG DATABASE_FILENAME

ENV APP_KEYS=$APP_KEYS \
    API_TOKEN_SALT=$API_TOKEN_SALT \
    ADMIN_JWT_SECRET=$ADMIN_JWT_SECRET \
    JWT_SECRET=$JWT_SECRET \
    DATABASE_FILENAME=$DATABASE_FILENAME

RUN pnpm build

EXPOSE 1337
CMD ["pnpm", "run", "start"]
